FROM ubuntu:20.04
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
LABEL MAINTAINER="jen@simenvi.com.tw"
# COPY myapp/ /usr/src/app

WORKDIR /usr/src/main
RUN (apt update &&  apt upgrade -y )\
    && (apt install -y vim && apt install -y net-tools)
# && (apt install software-properties-common -y)\
# && (add-apt-repository ppa:deadsnakes/ppa)\
# && (apt install wget)
# && (wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh)\
COPY Miniconda3-latest-Linux-x86_64.sh /usr/src/main/
RUN bash Miniconda3-latest-Linux-x86_64.sh -b \
    && conda init \
    && . /root/.bashrc  \
    && conda create -n py310 python=3.10 \
    && conda activate py310 \
    && pip install -U pip \
    && pip install sqlalchemy geopandas fastapi uvicorn gunicorn ipython tqdm\
    && conda install -y pymssql==2.2.4 pymongo pyodbc\
    && echo 'conda activate py310' >> /root/.bashrc



# RUN echo "source activate env" > ~/.bashrc
# ENV PATH /opt/conda/envs/env/bin:$PATH
# RUN conda activate py310
# CMD ["bash", "test.sh"]
# CMD ["/root/miniconda3/envs/py310/bin/uvicorn", "--port", "8000", "--host", "0.0.0.0", "runApiServer:app"]
# ENTRYPOINT /root/miniconda3/envs/py310/bin/uvicorn --port 8000 --host 0.0.0.0 runApiServer:app


# # FROM python:3.10.4-alpine3.15
# # FROM robd003/python3.10:latest
# FROM quartile/basepython
# WORKDIR /app
# ADD ./explosive_backend/ /app
# # RUN pip install flask
# # EXPOSE 5001
# # CMD  export FLASK_APP=run.py && flask run --reload --debugger --host 0.0.0.0 --port 5001
