FROM node:latest as build-stage
WORKDIR /app
COPY ./explosive_web/package*.json ./
COPY ./explosive_web/ .
RUN npm install && npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app/explosivemap
COPY nginx.conf /etc/nginx/nginx.conf
