FROM ubuntu:20.04
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
LABEL MAINTAINER="sjenwork@gmail.com"

WORKDIR /usr/src/main
RUN (apt update &&  apt upgrade -y )\
    && (apt install -y vim && apt install -y net-tools)


COPY Miniconda3-latest-Linux-x86_64.sh /usr/src/main/
RUN bash Miniconda3-latest-Linux-x86_64.sh -b \
    && conda init \
    && . /root/.bashrc  \
    && conda create -n py310 python=3.10 \
    && conda activate py310 \
    && pip install -U pip \
    && pip install sqlalchemy geopandas fastapi uvicorn gunicorn ipython tqdm pymssql==2.2.4\
    && conda install -y pymongo pyodbc\
    && echo 'conda activate py310' >> /root/.bashrc

